---
- name: Validate server authentication input provided by user
  when:
    - (auth_token is not defined)
  fail:
    msg: auth_token is mandatory

- name: Copy results to output file
  copy:
    content: "{{ result_attr | to_nice_json }}"
    dest: "{{ template }}.json"
